image: java:8

variables:
  ANDROID_COMPILE_SDK: "28"
  ANDROID_BUILD_TOOLS: "28.0.2"
  ANDROID_SDK_TOOLS:   "4333796"

commitVerificaiton:
  script:
    - ./gradlew ktlint detekt lintDebug testDebugUnitTest --stacktrace
  only:
    - merge_requests
  except:
    - /v\d+\.\d+\.\d+\.\d+(r|t)$/